<footer>
    <div class="row">
        <aside class="left_aligned">
            <h1>NetVision</h1>
            <p>Connecting the world with secure, innovative network solutions.</p>
        </aside>
        <aside class="left_aligned">
            <h3>Contact Us</h3>
            <!-- Group Jira site -->
            <div class="row">
                <img src="images/svg/jira.svg" alt="Jira">
                <p><a href="https://group2cos10026.atlassian.net/jira/software/projects/SCRUM/boards/1"
                        target="_blank">Our
                        Jira
                        board</a></p>
            </div>
            <!-- Group GitHub repository -->
            <div class="row">
                <img src="images/svg/github.svg" alt="GitHub">
                <p><a href="https://github.com/nguyenducnam06/Group-2-COS10026" target="_blank">Our GitHub
                        repository</a></p>
            </div>
            <div class="row">
                <img src="images/svg/mail.svg" alt="Mail">
                <p><a href="mailto:info@netvision.com.au">info@netvision.com.au</a></p>
            </div>
            <div class="row">
                <img src="images/svg/phone.svg" alt="Phone">
                <p>+84 746 265 999</p>
            </div>
            <!-- Location source: Google Maps -->
            <div class="row">
                <img src="images/svg/location.svg" alt="Location">
                <p><a href="https://maps.app.goo.gl/DdpmDrBmuNDem2KX7" target="_blank">80 Duy Tan, Hanoi,
                        Vietnam</a>
                </p>
            </div>
        </aside>
        <aside class="left_aligned">
            <h3>Follow Us</h3>
            <!-- Social media platforms: Facebook, Instagram, Twitter, LinkedIn -->
            <div class="row">
                <a href="https://www.facebook.com/" target="_blank"><img src="images/svg/facebook.svg"
                        alt="Facebook"></a>
                <a href="https://www.instagram.com/" target="_blank"><img src="images/svg/instagram.svg"
                        alt="Instagram"></a>
                <a href="https://www.x.com/" target="_blank"><img src="images/svg/twitter.svg" alt="Twitter"></a>
                <a href="https://www.linkedin.com/" target="_blank"><img src="images/svg/linkedin.svg"
                        alt="LinkedIn"></a>
            </div>
        </aside>
    </div>
</footer>