<header>
  <img src="images/svg/logo.svg" alt="NetVision Logo" class="logo" />
  <h3>NetVision</h3>
  <nav>
    <ul>
      <li><a href="index.php">Home</a></li>
      <li><a href="jobs.php">Job Description</a></li>
      <li><a href="apply.php">Apply</a></li>
      <li><a href="about.php">About Us</a></li>
    </ul>
  </nav>
  <ul>
    <li><a href="mailto:info@netvision.com.au">info@netvision.com.au</a></li>
  </ul>
</header>
