<![CDATA[ <meta charset="UTF-8"> <meta name="viewport"
content="width=device-width, initial-scale=1.0"> <meta name="description"
content="NetVision - <?php echo $pageDescription; ?>"> <meta name="keywords"
content="NetVision, Careers, Network Jobs, Recruitment, Opportunities, IT Jobs">
<meta name="author" content="Group 2 - COS10026"> <title>NetVision - <?php echo
$pageTitle; ?></title> <link rel="stylesheet" href="styles/style.css"> <?php if
(isset($pageSpecificStyle)): ?> <link rel="stylesheet" href="styles/<?php echo
$pageSpecificStyle; ?>.css"> <?php endif; ?> <link rel="preconnect"
href="https://fonts.googleapis.com"> <link rel="preconnect"
href="https://fonts.gstatic.com" crossorigin> <link
href="https://fonts.googleapis.com/css2?family=Cal+Sans&display=swap"
rel="stylesheet"> <link
href="https://fonts.googleapis.com/css2?family=Cal+Sans&family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap"
rel="stylesheet"> ]]>
